name: Deploy Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install and check
        run: |
          npm ci
          npm run lint
          npm run typecheck

      - id: "auth"
        uses: "google-github-actions/auth@v3"
        with:
          credentials_json: ${{ secrets.GCP_SA_DEV_KEY }}
          service_account: "gcp-sa-dev-key@excalidraw-json-dev.iam.gserviceaccount.com"

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v3"
        with:
          deliverables: app.yaml
          project_id: excalidraw-json-dev
          promote: true
